In [86]:
import datetime
import pandas as pd
import yahoo_fin.stock_info as si
from yahoofinancials import YahooFinancials

# Get Historical Earnings Data:

In [98]:
aapl_earnings_hist = si.get_earnings_history("aapl")
pd.DataFrame.from_dict(aapl_earnings_hist)

df = pd.DataFrame.from_dict(aapl_earnings_hist)

df

,ticker,companyshortname,startdatetime,startdatetimetype,epsestimate,epsactual,epssurprisepct,timeZoneShortName,gmtOffsetMilliSeconds,quoteType
0,AAPL,Apple Inc,2022-07-25T20:00:00.000Z,AMC,1.16,NaN,NaN,EDT,-14400000,EQUITY
1,AAPL,Apple Inc.,2022-04-28T16:30:00.000Z,TAS,1.43,1.52,6.44,EDT,-14400000,EQUITY
2,AAPL,Apple Inc.,2022-01-27T16:30:00.000Z,TAS,1.89,2.10,11.17,EST,-18000000,EQUITY
3,AAPL,Apple Inc.,2021-10-28T16:30:00.000Z,TAS,1.24,1.24,0.32,EDT,-14400000,EQUITY
4,AAPL,Apple Inc.,2021-07-27T16:30:00.000Z,TAS,1.01,1.30,29.10,EDT,-14400000,EQUITY
...,...,...,...,...,...,...,...,...,...,...
95,AAPL,Apple Inc.,1997-10-15T04:00:00.000Z,TAS,0.00,0.00,-50.44,EDT,-14400000,EQUITY
96,AAPL,Apple Inc.,1997-07-16T04:00:00.000Z,TAS,-0.02,-0.02,26.79,EDT,-14400000,EQUITY
97,AAPL,Apple Inc.,1997-04-16T04:00:00.000Z,TAS,-0.04,-0.05,-18.29,EDT,-14400000,EQUITY
98,AAPL,Apple Inc.,1997-01-15T05:00:00.000Z,TAS,-0.02,-0.03,-48.31,EST,-18000000,EQUITY
99,AAPL,Apple Inc.,1996-10-16T04:00:00.000Z,TAS,-0.01,0.00,118.29,EDT,-14400000,EQUITY

In [99]:
df.to_excel('AAPL_Earnings_Data.xlsx')

# Get analyst info:

In [91]:
from yahoo_fin.stock_info import get_analysts_info
get_analysts_info('aapl')

{'Earnings Estimate':   Earnings Estimate  Current Qtr. (Jun 2022)  Next Qtr. (Sep 2022)  \
 0   No. of Analysts                    29.00                 28.00
 1     Avg. Estimate                     1.16                  1.32
 2      Low Estimate                     1.07                  1.21
 3     High Estimate                     1.32                  1.44
 4      Year Ago EPS                     1.30                  1.24

    Current Year (2022)  Next Year (2023)
 0                40.00             40.00
 1                 6.14              6.55
 2                 5.93              5.91
 3                 6.63              7.35
 4                 5.61              6.14  ,
 'Revenue Estimate':           Revenue Estimate Current Qtr. (Jun 2022) Next Qtr. (Sep 2022)  \
 0          No. of Analysts                      26                   25
 1            Avg. Estimate                  82.43B               90.39B
 2             Low Estimate                  78.88B                86.4B
 3            High Estimate                  88.41B               96.45B
 4           Year Ago Sales                     NaN               83.36B
 5  Sales Growth (year/est)                     NaN                8.40%

   Current Year (2022) Next Year (2023)
 0                  40               40
 1             393.82B           415.8B
 2              387.2B          393.77B
 3             402.65B          440.47B
 4             365.82B          393.82B
 5               7.70%            5.60%  ,
 'Earnings History':   Earnings History 6/29/2021 9/29/2021 12/30/2021 3/30/2022
 0         EPS Est.      1.01      1.24       1.89      1.43
 1       EPS Actual       1.3      1.24        2.1      1.52
 2       Difference      0.29         0       0.21      0.09
 3       Surprise %    28.70%     0.00%     11.10%     6.30%,
 'EPS Trend':           EPS Trend  Current Qtr. (Jun 2022)  Next Qtr. (Sep 2022)  \
 0  Current Estimate                     1.16                  1.32
 1        7 Days Ago                     1.16                  1.33
 2       30 Days Ago                     1.16                  1.33
 3       60 Days Ago                     1.25                  1.37
 4       90 Days Ago                     1.25                  1.37

    Current Year (2022)  Next Year (2023)
 0                 6.14              6.55
 1                 6.14              6.56
 2                 6.15              6.56
 3                 6.17              6.57
 4                 6.16              6.56  ,
 'EPS Revisions':        EPS Revisions  Current Qtr. (Jun 2022)  Next Qtr. (Sep 2022)  \
 0     Up Last 7 Days                      NaN                   NaN
 1    Up Last 30 Days                      NaN                   NaN
 2   Down Last 7 Days                      NaN                   NaN
 3  Down Last 30 Days                      1.0                   1.0

    Current Year (2022)  Next Year (2023)
 0                  NaN               1.0
 1                  1.0               3.0
 2                  NaN               NaN
 3                  2.0               1.0  ,
 'Growth Estimates':            Growth Estimates     AAPL  Industry  Sector(s)  S&P 500
 0              Current Qtr.  -10.80%       NaN        NaN      NaN
 1                 Next Qtr.    6.50%       NaN        NaN      NaN
 2              Current Year    9.40%       NaN        NaN      NaN
 3                 Next Year    6.70%       NaN        NaN      NaN
 4  Next 5 Years (per annum)    9.91%       NaN        NaN      NaN
 5  Past 5 Years (per annum)    8.42%       NaN        NaN      NaN}

# Get balance Sheet data:

In [67]:
from yahoo_fin.stock_info import get_balance_sheet 
df = get_balance_sheet('aapl', yearly = False)

df

#Quarterly balance sheet data.

endDate,2022-03-26,2021-12-25,2021-09-25,2021-06-26
Breakdown,,,,
totalLiab,283263000000,309259000000,287912000000,265560000000
totalStockholderEquity,67399000000,71932000000,63090000000,64280000000
otherCurrentLiab,58168000000,57043000000,53577000000,51306000000
totalAssets,350662000000,381191000000,351002000000,329840000000
commonStock,61181000000,58424000000,57365000000,54989000000
otherCurrentAssets,15809000000,18112000000,14111000000,13641000000
retainedEarnings,12712000000,14435000000,5562000000,9233000000
otherLiab,52432000000,55056000000,43050000000,38354000000
treasuryStock,-6494000000,-927000000,163000000,58000000
otherAssets,51959000000,50109000000,38762000000,44854000000
cash,28098000000,37119000000,34940000000,34050000000
totalCurrentLiabilities,127508000000,147574000000,125481000000,107754000000
shortLongTermDebt,9659000000,11169000000,9613000000,8039000000
otherStockholderEquity,-6494000000,-927000000,163000000,58000000
propertyPlantEquipment,39304000000,39245000000,49527000000,38615000000
totalCurrentAssets,118180000000,153154000000,134836000000,114423000000
longTermInvestments,141219000000,138683000000,127877000000,131948000000
netTangibleAssets,67399000000,71932000000,63090000000,64280000000
shortTermInvestments,23413000000,26794000000,27699000000,27646000000
netReceivables,45400000000,65253000000,51506000000,33908000000
longTermDebt,103323000000,106629000000,109106000000,105752000000
inventory,5460000000,5876000000,6580000000,5178000000
accountsPayable,52682000000,74362000000,54763000000,40409000000

# Get Cash flow data:

In [87]:
from yahoo_fin.stock_info import get_balance_sheet
df = get_balance_sheet('aapl')
df

#yearly cash flow data.

endDate,2021-09-25,2020-09-26,2019-09-28,2018-09-29
Breakdown,,,,
totalLiab,287912000000,258549000000,248028000000,258578000000
totalStockholderEquity,63090000000,65339000000,90488000000,107147000000
otherCurrentLiab,53577000000,47867000000,43242000000,39293000000
totalAssets,351002000000,323888000000,338516000000,365725000000
commonStock,57365000000,50779000000,45174000000,40201000000
otherCurrentAssets,14111000000,11264000000,12352000000,12087000000
retainedEarnings,5562000000,14966000000,45898000000,70400000000
otherLiab,43050000000,46108000000,50503000000,48914000000
treasuryStock,163000000,-406000000,-584000000,-3454000000
otherAssets,38762000000,33952000000,32978000000,22283000000
cash,34940000000,38016000000,48844000000,25913000000
totalCurrentLiabilities,125481000000,105392000000,105718000000,115929000000
shortLongTermDebt,9613000000,8773000000,10260000000,8784000000
otherStockholderEquity,163000000,-406000000,-584000000,-3454000000
propertyPlantEquipment,49527000000,45336000000,37378000000,41304000000
totalCurrentAssets,134836000000,143713000000,162819000000,131339000000
longTermInvestments,127877000000,100887000000,105341000000,170799000000
netTangibleAssets,63090000000,65339000000,90488000000,107147000000
shortTermInvestments,27699000000,52927000000,51713000000,40388000000
netReceivables,51506000000,37445000000,45804000000,48995000000
longTermDebt,109106000000,98667000000,91807000000,93735000000
inventory,6580000000,4061000000,4106000000,3956000000
accountsPayable,54763000000,42296000000,46236000000,55888000000

In [57]:
cash_flow = si.get_cash_flow("aapl", yearly = False)
cash_flow

#yearly cash flow data.

endDate,2022-03-26,2021-12-25,2021-09-25,2021-06-26
Breakdown,,,,
investments,-6.390000e+09,-1.292900e+10,4.608000e+09,5.747000e+09
changeToLiabilities,-2.139800e+10,2.027500e+10,1.405000e+10,3.070000e+08
totalCashflowsFromInvestingActivities,-9.265000e+09,-1.610600e+10,8.350000e+08,3.572000e+09
netBorrowings,-1.751000e+09,-1.000000e+09,3.220000e+09,3.220000e+09
totalCashFromFinancingActivities,-2.835100e+10,-2.815900e+10,-2.038200e+10,-2.939600e+10
changeToOperatingActivities,9.486000e+09,-1.049700e+10,-5.602000e+09,-6.048000e+09
netIncome,2.501000e+10,3.463000e+10,2.055100e+10,2.174400e+10
changeInCash,-9.450000e+09,2.701000e+09,6.530000e+08,-4.730000e+09
repurchaseOfStock,-2.296100e+10,-2.336600e+10,-2.044900e+10,-2.559500e+10
totalCashFromOperatingActivities,2.816600e+10,4.696600e+10,2.020000e+10,2.109400e+10
depreciation,2.737000e+09,2.697000e+09,2.989000e+09,2.832000e+09
otherCashflowsFromInvestingActivities,-1.940000e+08,-3.740000e+08,-5.300000e+08,-7.800000e+07
dividendsPaid,-3.595000e+09,-3.732000e+09,-3.640000e+09,-3.767000e+09
changeToInventory,3.840000e+08,6.810000e+08,-1.429000e+09,1.300000e+07
changeToAccountReceivables,9.476000e+09,-3.934000e+09,-8.809000e+09,1.031000e+09
otherCashflowsFromFinancingActivities,-4.400000e+07,-6.100000e+07,-5.700000e+07,-3.400000e+07
changeToNetincome,2.471000e+09,3.114000e+09,-1.550000e+09,1.215000e+09
capitalExpenditures,-2.514000e+09,-2.803000e+09,-3.223000e+09,-2.093000e+09
issuanceOfStock,NaN,NaN,5.440000e+08,5.440000e+08

# Get Income statement data:

In [72]:
income_statement = si.("aapl")
income_statement

endDate,2021-09-25,2020-09-26,2019-09-28,2018-09-29
Breakdown,,,,
researchDevelopment,21914000000,18752000000,16217000000,14236000000
effectOfAccountingCharges,None,None,None,None
incomeBeforeTax,109207000000,67091000000,65737000000,72903000000
minorityInterest,None,None,None,None
netIncome,94680000000,57411000000,55256000000,59531000000
sellingGeneralAdministrative,21973000000,19916000000,18245000000,16705000000
grossProfit,152836000000,104956000000,98392000000,101839000000
ebit,108949000000,66288000000,63930000000,70898000000
operatingIncome,108949000000,66288000000,63930000000,70898000000
otherOperatingExpenses,None,None,None,None
interestExpense,-2645000000,-2873000000,-3576000000,-3240000000
extraordinaryItems,None,None,None,None
nonRecurring,None,None,None,None
otherItems,None,None,None,None
incomeTaxExpense,14527000000,9680000000,10481000000,13372000000
totalRevenue,365817000000,274515000000,260174000000,265595000000
totalOperatingExpenses,256868000000,208227000000,196244000000,194697000000
costOfRevenue,212981000000,169559000000,161782000000,163756000000
totalOtherIncomeExpenseNet,258000000,803000000,1807000000,2005000000
discontinuedOperations,None,None,None,None
netIncomeFromContinuingOps,94680000000,57411000000,55256000000,59531000000
netIncomeApplicableToCommonShares,94680000000,57411000000,55256000000,59531000000

In [75]:
income_statement.loc["netIncome"]

endDate
2021-09-25    94680000000
2020-09-26    57411000000
2019-09-28    55256000000
2018-09-29    59531000000
Name: netIncome, dtype: object